name: Sync to other branches

on:
  push:
    branches:
      - candidate

permissions:
  issues: write
  contents: write

jobs:
  sync-edge:
    name: 🔄 Sync candidate branch to edge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: edge
    - name: Merge from candidate
      run: |
        git pull
        git config --global user.name "Snapcrafters[bot]"
        git config --global user.email "bot@bot.bot"

        git merge origin/candidate -m 'chore: merge candidate to edge'
        git push
